@base_url = https://localhost:7234/api

# FUNCIONÁRIO ######################################

### Criação de um novo funcionário
POST {{base_url}}/funcionario/cadastrar
Content-Type: application/json

{
    "nome": "Fudido",
    "cpf" : "15023545784"
}

### Obtenção de todos os funcionários
GET {{base_url}}/funcionario/listar

# FOLHA ############################################

### Criação de uma nova folha
POST {{base_url}}/folhapagamento/cadastrar
Content-Type: application/json

{
    "valor": 10,
    "quantidade" : 10,
    "mes" : 10,
    "ano" : 2023,
    "funcionarioId" : 11
}

### Obtenção de todas as folhas
GET {{base_url}}/folhapagamento/listar

### Obtenção de uma folha
GET {{base_url}}/folhapagamento/buscar/15023545784/10/2023